---
# tasks file for masters
- name: Install Docker
  apt: 
    name: "{{ docker }}"
    state: present
    update_cache: true

- name: Copy config file with external etcd
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Copy config file with external etcd 
  copy:
    src: kubeadm-config.yaml
    dest: /etc/kubernetes/kubeadm-config.yaml

- name: daemon-reload
  shell: |
    systemctl daemon-reload
    systemctl restart docker
    systemctl restart kubelet



- name: Init kubeadm-config.yaml
  shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml --ignore-preflight-errors=all

- name: Run on kubeadm for root user
  shell: | 
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config

- name: Deploy cni flannel
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

 
